# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyautogui
from time import sleep

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(170, -10, 761, 131))
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic Thin")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 100, 468, 97))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleLabel_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic Thin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel_2.setFont(font)
        self.titleLabel_2.setObjectName("titleLabel_2")
        self.verticalLayout_3.addWidget(self.titleLabel_2)
        self.dimensionButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.dimensionButton.setObjectName("dimensionButton")
        self.verticalLayout_3.addWidget(self.dimensionButton)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleLabel_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic Thin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel_3.setFont(font)
        self.titleLabel_3.setObjectName("titleLabel_3")
        self.verticalLayout_2.addWidget(self.titleLabel_3)
        self.xEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.xEdit.setObjectName("xEdit")
        self.verticalLayout_2.addWidget(self.xEdit)
        self.yEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.yEdit.setObjectName("yEdit")
        self.verticalLayout_2.addWidget(self.yEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(360, 210, 335, 153))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titleLabel_4 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic Thin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel_4.setFont(font)
        self.titleLabel_4.setObjectName("titleLabel_4")
        self.verticalLayout_4.addWidget(self.titleLabel_4)
        self.anzahlEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.anzahlEdit.setObjectName("anzahlEdit")
        self.verticalLayout_4.addWidget(self.anzahlEdit)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sekundenButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.sekundenButton.setObjectName("sekundenButton")
        self.verticalLayout.addWidget(self.sekundenButton)
        self.minutenButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.minutenButton.setObjectName("minutenButton")
        self.verticalLayout.addWidget(self.minutenButton)
        self.stundenButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.stundenButton.setObjectName("stundenButton")
        self.verticalLayout.addWidget(self.stundenButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(410, 370, 244, 124))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.titleLabel_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic Thin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel_5.setFont(font)
        self.titleLabel_5.setObjectName("titleLabel_5")
        self.verticalLayout_6.addWidget(self.titleLabel_5)
        self.loopCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.loopCheck.setObjectName("loopCheck")
        self.verticalLayout_6.addWidget(self.loopCheck)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.startButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_5.addWidget(self.startButton)
        self.titleLabel_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic Thin")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel_6.setFont(font)
        self.titleLabel_6.setObjectName("titleLabel_6")
        self.verticalLayout_5.addWidget(self.titleLabel_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 25))
        self.menubar.setObjectName("menubar")
        self.menuHilfe = QtWidgets.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_ber = QtWidgets.QAction(MainWindow)
        self.action_ber.setObjectName("action_ber")
        self.actionHInweise = QtWidgets.QAction(MainWindow)
        self.actionHInweise.setObjectName("actionHInweise")
        self.menuHilfe.addAction(self.actionHInweise)
        self.menuHilfe.addAction(self.action_ber)
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.dimensionButton.clicked.connect(self.setResolution)
        self.startButton.clicked.connect(self.gogo)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HOPPS Bot"))
        self.titleLabel.setText(_translate("MainWindow", "itslearning Bot für gute Mitarbeitsnoten"))
        self.titleLabel_2.setText(_translate("MainWindow", "1: Auflösung ermitteln"))
        self.dimensionButton.setText(_translate("MainWindow", "Bildschirmauflösung ermitteln"))
        self.titleLabel_3.setText(_translate("MainWindow", "Alternativ: Auflösung manuell bearbeiten"))
        self.titleLabel_4.setText(_translate("MainWindow", "2: Wie Zeit möchtest du in jedem Kurs verbringen?"))
        self.sekundenButton.setText(_translate("MainWindow", "Sekunden"))
        self.minutenButton.setText(_translate("MainWindow", "Minuten"))
        self.stundenButton.setText(_translate("MainWindow", "Stunden"))
        self.titleLabel_5.setText(_translate("MainWindow", "4: Mitarbeitsnoten verbessern!"))
        self.loopCheck.setText(_translate("MainWindow", "Endlosschleife"))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.titleLabel_6.setText(_translate("MainWindow", "Beenden mit STRG+C in der Konsole"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.action_ber.setText(_translate("MainWindow", "Über"))
        self.action_ber.setStatusTip(_translate("MainWindow", "Über dieses Programm"))
        self.action_ber.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.actionHInweise.setText(_translate("MainWindow", "HInweise"))
    
    def endProgram(self):
        exit()
    def setResolution(self):
        self.xEdit.setText(str(size.width()))
        self.yEdit.setText(str(size.height()))
        if(self.sekundenButton.isChecked() == True):
            print("SOOOS")
        else:
            print("SEEES")

    def stopClicked(self):
        self.stop = True
    

    def gogo(self):
        self.stop = False
        screenResX = int(self.xEdit.text())
        screenResY = int(self.yEdit.text())
        if(self.sekundenButton.isChecked()):
            timeout = int(self.anzahlEdit.text())
            print(timeout)
        elif(self.minutenButton.isChecked()):
            timeout = int(self.anzahlEdit.text())*60
            print(timeout)
        elif(self.stundenButton.isChecked()):
            timeout = int(self.anzahlEdit.text())*60*60
            print(timeout)
        
        def getX(x):
            x1 = 320 + (x*310) - 310
            x2 = x1 / screenResX
            return x2 * screenResX


        def getY(y):
            y1 = 446 + (y*310) - 310
            y2 = y1 / screenResY
            return y2 * screenResY

        def clickCourse(x,y):
            pyautogui.moveTo(getX(x), getY(y))
            pyautogui.click()

        def goStart():
            pyautogui.moveTo(0.016625*screenResX,0.1029518*screenResY)
            pyautogui.click()

        def scrolldown():
            pyautogui.moveTo(0.9963541*screenResX,0.201851851*screenResY)
            pyautogui.dragRel(0,0.37037037*screenResY,duration=1)

        print(pyautogui.position())
        abbruch = False
        #clickCourse(1,1)
        while abbruch == False:
            for i in range(4):
                for i1 in range(5):
                    goStart()
                    sleep(3)
                    if (i+1 > 2):
                        scrolldown()
                        i=i-1
                        clickCourse(i1+1, i)
                        i=i+1
                    else:
                        clickCourse(i1 + 1,i + 1)
                    sleep(timeout)
            goStart()
            sleep(3)
            if (self.loopCheck.isChecked()==False):
                abbruch = True




       

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    screen = app.primaryScreen()
    size = screen.size()
    
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
